# Generated by Django 4.2.7 on 2023-11-26 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0002_alter_resultado_ia_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='pdc',
        ),
        migrations.AddField(
            model_name='usuario',
            name='modalidade_ensino',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='usuario',
            name='municipio_beneficiario',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nome_curso',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nome_ies',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nome_turno_curso',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='usuario',
            name='sigla_uf_beneficiario',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='raca',
            field=models.CharField(choices=[('Branca', 'Branca'), ('Preta', 'Preta'), ('Amarela', 'Amarela'), ('Parda', 'Parda'), ('Indígena', 'Indígena')], max_length=8),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='regiao',
            field=models.CharField(choices=[('Norte', 'Norte'), ('Nordeste', 'Nordeste'), ('Sul', 'Sul'), ('Sudeste', 'Sudeste'), ('Centro-Oeste', 'Centro-Oeste')], max_length=35),
        ),
    ]
